services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - /var/log/product-service:/mnt/tracing/product-service:ro
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 13133:13133
      - 4319:4318

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml:ro
      - /var/log/product-service:/var/log/product-service:ro
    command:
      - "--config.file=/etc/promtail/promtail.yaml"
      - "--config.expand-env=true"

  pyroscope:
    image: grafana/pyroscope
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    logging:
      driver: json-file

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
