server:
  log_level: debug
  http_listen_port: 9081
  grpc_listen_port: 1

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          app: product-service
          __path__: /var/log/product-service/product-service-8083.json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            mdc: mdc
            logger: logger
            message: message
      - regex:
          expression: (traceId=(?P<trace_id>([a-zA-Z0-9]{32})))|(spanId=(?P<span_id>([a-zA-Z0-9]{16})))|(rqid=(?P<request_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))|,\s|.*
          source: mdc
      - labels:
          level:
          thread:
          mdc:
          trace_id:
          span_id:
          request_id:
          logger:
      - timestamp:
          source: timestamp
          format: 2006-01-05 10:10:10.000
      - output:
          source: message
